spring.application.name=studentmanagement


# MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/sms_db
spring.datasource.username=root
spring.datasource.password=taimoor
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=dGhpcy1pcy1hLXNlY3VyZS1rZXktZm9yLXNwcmluZy1ib290LWp3dC1hdXRoZW50aWNhdGlvbi1leGFtcGxl
jwt.expiration=86400000